---
output:
  pdf_document: default
  html_document: default
  word_document: default
---
```{r}
library(dplyr)
library(ggplot2)
library(moments)
options(scipen = 999)
```

```{r}
houses = read.csv("house_price.csv", stringsAsFactors = TRUE)
dim(houses)
```

```{r}
# Operazioni preliminari:
# 1. Verifico quali righe e colonne hanno troppi valori mancanti
# 2. Rimuovo righe e colonne con troppi valori mancanti
# 3. Divido il dataset in due parti: una con le variabili numeriche e una con le variabili categoriche

quant_cont_cols = c("LotFrontage", "LotArea", "MasVnrArea", "BsmtFinSF1", "BsmtFinSF2", "BsmtUnfSF", "TotalBsmtSF", "X1stFlrSF", "X2ndFlrSF", "LowQualFinSF", "GrLivArea", "GarageArea", "WoodDeckSF", "OpenPorchSF", "EnclosedPorch", "X3SsnPorch", "ScreenPorch")
qual_cols = c("MSSubClass", "MSZoning", "Street", "LotShape", "LandContour", "Utilities", "LotConfig", "LandSlope", "Neighborhood", "Condition1", "Condition2", "BldgType", "HouseStyle", "RoofStyle", "RoofMatl", "Exterior1st", "Exterior2nd", "MasVnrType", "ExterQual", "ExterCond", "Foundation", "BsmtQual", "BsmtCond", "BsmtExposure", "BsmtFinType1", "BsmtFinType2", "Heating", "HeatingQC", "CentralAir", "Electrical", "KitchenQual", "Functional", "FireplaceQu", "GarageType", "GarageFinish", "GarageQual", "GarageCond", "PavedDrive", "SaleType", "SaleCondition")
quant_disc_cols = c("BsmtFullBath", "BsmtHalfBath", "FullBath", "HalfBath", "BedroomAbvGr", "KitchenAbvGr", "TotRmsAbvGrd", "Fireplaces", "GarageCars")
year_cols = c("YearBuilt", "YearRemodAdd", "GarageYrBlt")
mark_cols = c("OverallQual", "OverallCond")

houses[, qual_cols[1]] = as.factor(houses[, qual_cols[1]])

quant_cont_vars = houses[, quant_cont_cols]
qual_vars = houses[, qual_cols]
quant_discr_vars = houses[, quant_disc_cols]
year_vars = houses[, year_cols]
mark_vars = houses[, mark_cols]
```


```{r}
cont_info = function (x, i) {
  if (colnames(quant_cont_vars[i]) != "LotFrontage" & colnames(quant_cont_vars[i]) != "LotArea") {
    x = x[x != 0]
  }
  print(colnames(quant_cont_vars[i]))
  print(summary(x))
  print("Skewness")
  print(skewness(x, na.rm = TRUE))
  print("Curtosi")
  print(kurtosis(x, na.rm = TRUE))
  par(mfrow = (c(1, 3)))
  boxplot(x, main = "Boxplot", xlab = "Value", horizontal = TRUE)
  plot(density(x, na.rm = T), main="Frequency", xlab = "Frequency", ylab = "Frequency")
  qqnorm(x, main = "QQ Plot")
  qqline(x)
  mtext(text=colnames(quant_cont_vars[i]), line = -1.75, outer = T, cex = 1.5)
}

disc_info = function(x, i) {
  print(colnames(quant_discr_vars[i]))
  print(summary(x, na.rm = T))
  par(mfrow = (c(1, 1)))
  barplot(prop.table(table(x)), main = colnames(quant_discr_vars[i]), xlab = "Value", ylab = "Frequency")
}

year_info = function(x, i) {
  par(mfrow = (c(1, 1)))
  print("Minimo")
  print(min(x, na.rm=T))
  print("Massimo")
  print(max(x, na.rm=T))
  print("Quantili")
  print(quantile(x, na.rm=T))
  hist(x, main = colnames(year_vars[i]), xlab = "Value", ylab = "Frequency")
}


mark_info = function(x, i) {
  par(mfrow = (c(1, 1)))
  print(colnames(mark_vars[i]))
  print("Minimo")
  print(min(x, na.rm=T))
  print("Massimo")
  print(max(x, na.rm=T))
  print("Quantili")
  print(quantile(x, na.rm=T))
  barplot(prop.table(table(x)), main = colnames(mark_vars[i]), xlab = "Value", ylab = "Frequency")
}


qual_info = function (x, i) {
  print(colnames(quant_cont_vars[i]))
  print(table(x))
  print(prop.table(table(x)))
  par(mfrow = (c(1, 2)))
  barplot(table(x), main = "Frequenze assolute", xlab = "Value", ylab = "Frequenze")
  barplot(prop.table(table(x)), main = "Frequenze relative", xlab = "Value", ylab = "Frequenze")
  mtext(text=colnames(quant_cont_vars[i]), line = -1.75, outer = T, cex = 1.5)
}
```

```{r}
for (i in seq_along(quant_cont_vars)) {
  cont_info(quant_cont_vars[, i], i)
}
```
